### ISSUE TITLE
opensnoop (toolsMode=standard) fails the BPF verifier

### ISSUE THREAD

**Issue by alban** [kinvolk/inspektor-gadget#244]
## Description

opensnoop (toolsMode=standard) fails the BPF verifier on Minikube with the docker driver.

But other gadgets like execsnoop work fine.

## Impact

opensnoop does not work.

Workaround: use `kubectl gadget deploy --tools-mode=auto` or `core`.

## Environment and steps to reproduce

Minikube with the docker driver on Fedora:
```
$ uname -r
5.12.6-300.fc34.x86_64

$ kubectl get node -o wide
NAME       STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION           CONTAINER-RUNTIME
minikube   Ready    master   15m   v1.18.3   172.17.0.3    <none>        Ubuntu 19.10   5.12.6-300.fc34.x86_64   docker://19.3.2
```

```
$ ./kubectl-gadget-linux-amd64 opensnoop -n default
bpf: Failed to load program: Permission denied
; KRETFUNC_PROBE(__x64_sys_open, struct pt_regs *regs, int ret)
0: (bf) r6 = r1
; KRETFUNC_PROBE(__x64_sys_open, struct pt_regs *regs, int ret)
1: (79) r9 = *(u64 *)(r6 +8)
2: (79) r1 = *(u64 *)(r6 +0)
func '__x64_sys_open' arg0 has btf_id 176 type STRUCT 'pt_regs'
; const char __user *filename = (char *)PT_REGS_PARM1(regs);
3: (79) r8 = *(u64 *)(r1 +112)
; u64 id = bpf_get_current_pid_tgid();
4: (85) call bpf_get_current_pid_tgid#14
5: (bf) r7 = r0
; u32 uid = bpf_get_current_uid_gid();
6: (85) call bpf_get_current_uid_gid#15
; current_task = (struct task_struct *)bpf_get_current_task();
7: (85) call bpf_get_current_task#35
; return current_task->nsproxy->mnt_ns->ns.inum;
8: (79) r1 = *(u64 *)(r0 +2952)
R0 invalid mem access 'inv'
processed 9 insns (limit 1000000) max_states_per_insn 0 total_states 1 peak_states 1 mark_read 0

HINT: The invalid mem access 'inv' error can happen if you try to dereference memory without first using bpf_probe_read_kernel() to copy it to the BPF stack. Sometimes the bpf_probe_read_kernel() is automatic by the bcc rewriter, other times you'll need to be explicit.

Traceback (most recent call last):
  File "/bin/gadgets/opensnoop", line 340, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 460, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1388, in _trace_autoload
    self.attach_kretfunc(fn_name=func_name)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1088, in attach_kretfunc
    fn = self.load_func(fn_name, BPF.TRACING)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 500, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program kretfunc____x64_sys_open: Permission denied

Error running command: command terminated with exit code 1
```

## Expected behavior

No verifier error.

**Comment by mauriciovasquezbernal** [comment]
This problem is related to BCC and not to the changes we've done in the last iterations. opensnoop uses kretfunc when it's available in the kernel. For some reason the BCC rewriter doesn't change `current_task->nsproxy->mnt_ns->ns.inum` to use btf_probe_read and hence the verifier complains about that. I'm not sure if this is supposed to happen or there is a problem in the BCC rewriter. I'll continue to investigate.
