### ISSUE TITLE
Standard implementation of trace/bind gadget is not working

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#826]
## Description

While testing https://github.com/kinvolk/inspektor-gadget/pull/797, I found that the standard implementation of the trace/bind gadget is not working. I tried to dig into this problem and found that the error is in the `bindsnoop` tool itself and not in the Inspektor-Gadget code. In particular, the `bindsnoop` tool fails only when using JSON format, which is the format we use when we execute it from Inspektor-Gadget.

It is important to remark that this error is not being forwarded to the Inspektor-Gadget and thus not to the user. It is because we are not capturing the stderr when running these tools from Inspektor-Gadget, see [here](https://github.com/kinvolk/inspektor-gadget/blob/dc146b599f9a101d70f9a3dae83a322f35a3d1a7/pkg/standardgadgets/trace/standardtracerbase.go#L66).

## Impact

If the CORE implementation of the trace/bind gadget doesn't work on a given node, then the standard implementation (which is the fallback) will not work either, and the user will not be able to use the gadget at all.

## Environment and steps to reproduce

It is enough to run the `bindsnoop` binary. I triggered the bind events using `nc` as described in [the gadget guide](https://github.com/kinvolk/inspektor-gadget/blob/main/docs/guides/trace/bind.md#how-to-use-it):

```bash
$ kubectl exec -ti -n gadget <gadget-pod> -- /bin/bash

# Using columns works
root@worker:/$ /usr/share/bcc/tools/bindsnoop
Tracing binds ... Hit Ctrl-C to end
     PID COMM         PROT ADDR            PORT   OPTS IF
  255430 nc           UNKN ::               4242 ...R.  0

# Using JSON doesn't
root@worker:/$ /usr/share/bcc/tools/bindsnoop --json
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/bcc/table.py", line 982, in raw_cb_
    callback(cpu, data, size)
  File "/usr/share/bcc/tools/bindsnoop", line 510, in print_ipv6_bind_event
    print_json(event, AF_INET6)
  File "/usr/share/bcc/tools/bindsnoop", line 450, in print_json
    "addr": inet_ntop(inetType, pack("I", event.saddr)).encode(),
struct.error: cannot convert argument to integer
```

## Additional information

When working on the solution, in case of need, it is possible to use the following example to test the standard implementation of the trace/bind gadget using the IG packages. It should be run in the gadget pod, which already has all the dependencies and the `bindsnoop` binary in place:

```golang
package main

import (
	"flag"
	"fmt"
	"os"
	"os/signal"

	"github.com/cilium/ebpf/rlimit"

	"github.com/kinvolk/inspektor-gadget/cmd/common/utils"
	cmdtrace "github.com/kinvolk/inspektor-gadget/cmd/kubectl-gadget/trace"

	containercollection "github.com/kinvolk/inspektor-gadget/pkg/container-collection"
	containerutils "github.com/kinvolk/inspektor-gadget/pkg/container-utils"
	"github.com/kinvolk/inspektor-gadget/pkg/container-utils/containerd"
	"github.com/kinvolk/inspektor-gadget/pkg/container-utils/docker"
	"github.com/kinvolk/inspektor-gadget/pkg/gadgets"
	"github.com/kinvolk/inspektor-gadget/pkg/gadgets/trace/bind/tracer"
	"github.com/kinvolk/inspektor-gadget/pkg/gadgets/trace/bind/types"
	standardtracer "github.com/kinvolk/inspektor-gadget/pkg/standardgadgets/trace/bind"

	containersmap "github.com/kinvolk/inspektor-gadget/pkg/gadgettracermanager/containers-map"
	tracercollection "github.com/kinvolk/inspektor-gadget/pkg/tracer-collection"
	eventtypes "github.com/kinvolk/inspektor-gadget/pkg/types"
)

func main() {
	// In some kernel versions it's needed to bump the rlimits to
	// use run BPF programs.
	if err := rlimit.RemoveMemlock(); err != nil {
		return
	}

	var containerName string
	flag.StringVar(&containerName, "containername", "", "Show only data from containers with that name")
	flag.Parse()

	// Create the container-map that will be used to enrich the events.
	containersMap, err := containersmap.NewContainersMap(gadgets.PinPath)
	if err != nil {
		fmt.Printf("error creating containers map: %s", err)
		return
	}
	defer containersMap.Close()

	// The trace-collection will allows us to filter by container
	containerCollection := containercollection.ContainerCollection{}
	tracerCollection, err := tracercollection.NewTracerCollection(&containerCollection)
	if err != nil {
		fmt.Printf("failed to create trace-collection: %s\n", err)
		return
	}
	defer tracerCollection.Close()

	// The container-collection will keep our container-map updated.
	containerEventFuncs := []containercollection.FuncNotify{
		containersMap.ContainersMapUpdater(),
		tracerCollection.TracerMapsUpdater(),
	}
	opts := []containercollection.ContainerCollectionOption{
		containercollection.WithPubSub(containerEventFuncs...),
		containercollection.WithLinuxNamespaceEnrichment(),
		containercollection.WithRuncFanotify(),
		containercollection.WithMultipleContainerRuntimesEnrichment([]*containerutils.RuntimeConfig{
			{Name: docker.Name},
			{Name: containerd.Name},
		}),
	}
	err = containerCollection.Initialize(opts...)
	if err != nil {
		fmt.Printf("failed to initialize container collection: %s\n", err)
		return
	}
	defer containerCollection.Close()

	traceName := "myTrace"
	err = tracerCollection.AddTracer(traceName, containercollection.ContainerSelector{
		Name: containerName,
	})
	if err != nil {
		fmt.Printf("failed to create tracer's mount ns map: %s", err)
		return
	}
	defer tracerCollection.RemoveTracer(traceName)

	mountNsMap, err := tracerCollection.TracerMountNsMap(traceName)
	if err != nil {
		fmt.Printf("failed to find tracer's mount ns map: %s", err)
		return
	}

	outputConfig := utils.OutputConfig{
		// Use JSON format
		OutputMode: utils.OutputModeJSON,
	}

	parser := cmdtrace.NewBindParser(&outputConfig)

	if outputConfig.OutputMode != utils.OutputModeJSON {
		fmt.Println(parser.BuildColumnsHeader())
	}

	// Define a callback to be called each time there is an event.
	eventCallback := func(event types.Event) {
		// This special case will not be needed soon, see
		// https://github.com/kinvolk/inspektor-gadget/pull/796.
		if event.Type != eventtypes.NORMAL {
			utils.ManageSpecialEvent(event.Event, outputConfig.Verbose)
			return
		}

		fmt.Println(parser.TransformEvent(&event))
	}

	config := &tracer.Config{
		MountnsMap: mountNsMap,
	}
	t, err := standardtracer.NewTracer(config, eventCallback)
	if err != nil {
		fmt.Printf("error creating tracer: %s\n", err)
		return
	}

	// Wait for SIGINT
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)

	<-c

	// Clean up everything before exiting.
	t.Stop()
}
```

**Comment by mauriciovasquezbernal** [comment]
I turned to be an easy one to fix -> https://github.com/kinvolk/bcc/pull/23. Will update the BCC version here once that PR is merged.
